//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REEntities : DbContext
    {
        public REEntities()
            : base("name=REEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<ListOfInsuranceCompany> ListOfInsuranceCompanys { get; set; }
        public virtual DbSet<ListOfService> ListOfServices { get; set; }
        public virtual DbSet<ListOfType> ListOfTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<ListOfGender> ListOfGenders { get; set; }
        public virtual DbSet<ListOfNationality> ListOfNationalities { get; set; }
        public virtual DbSet<Logging> Loggings { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
